Iter5
vpbuyanov/short-url pull request #5
Opened 2024-05-05 13:38 UTC by vpbuyanov

2024-05-07 06:50 UTC, s-shpak commented on cmd/shortener/main.go
> +		panic(err)
Не надо паниковать

2024-05-07 06:51 UTC, s-shpak commented on cmd/shortener/main.go
> +	logger := logrus.New()
Инициализацию логгера стоит поместить в отдельную функцию

2024-05-07 06:52 UTC, s-shpak commented on configs/config.go
Этот файл должен лежать либо в `cmd/shortener`, либо в `internal`

2024-05-07 06:54 UTC, s-shpak commented on Makefile
> +dev:
Добавляй аттрибут `.PHONY` к таргетам: https://www.gnu.org/software/make/manual/html_node/Phony-Targets.html

2024-05-07 06:56 UTC, s-shpak commented on internal/app/app.go
> +func (app *app) Run(ctx context.Context, log *logrus.Logger) error {
Почему ты поределил сигнатуру так (с возвращаемой ошибкой), если эта функция ее не возвращает ?

2024-05-07 06:56 UTC, s-shpak commented on internal/server/server.go
> +	if err != nil {
Ошибку надо пробрасывать наверх, см. видео про ошибки: https://app.pachca.com/chats/9180496?message=234290731

2024-05-07 06:58 UTC, s-shpak commented on internal/services/url.go
> +func New() URL {
На вебинаре мы обсуждали, что:
1. функции практически всегда возвращают структуры, а принимают на вход интерфейс
2. Интерфейсы в Go определяются там, где они используются

Исправь код согласно этим принципам

2024-05-07 06:59 UTC, s-shpak commented on internal/services/url.go
> +	newUrls["abcdefgG12"] = "https://google.com"
Зачем это ?

2024-05-07 07:00 UTC, s-shpak commented on internal/services/url.go
> +		switch randNumber {
Сложно и кажется, что дорого. Проще определить алфавит символов и случайным образом выбирать символ из него

2024-05-07 07:01 UTC, s-shpak commented on internal/services/url.go
> +func (u *url) generateURL() string {
Почему этот метод определен на уровне хранилища ? Кажется, что логика хранилища не должна смешиваться с логикой генерации коротких URL

2024-05-07 07:01 UTC, s-shpak commented on internal/handlers/handlers.go
> +	url := services.New()
Используй Dependency Injection здесь, передавай хранилище в конструктор

2024-05-07 07:02 UTC, s-shpak commented on internal/services/url.go
> +	for {
Стоит остановиться после нескольких попыток

2024-05-07 07:07 UTC, s-shpak requested changes
См. комментарии

2024-05-07 08:15 UTC, vpbuyanov commented on cmd/shortener/main.go
> +		panic(err)
а почему панику нельзя сделать на уровне main?

2024-05-07 08:17 UTC, vpbuyanov commented on internal/app/app.go
> +func (app *app) Run(ctx context.Context, log *logrus.Logger) error {
потому что в дальнейшем можно инициализировать репозитории или юскейсы которые могут отдать ошибку

2024-05-07 08:18 UTC, vpbuyanov commented on internal/server/server.go
> +	if err != nil {
да пропустил момент и как раз тут если возвращать то в App будет тоже возвращаться ошибка

2024-05-07 08:22 UTC, vpbuyanov commented on internal/services/url.go
> +func (u *url) generateURL() string {
согласен

2024-05-07 08:30 UTC, vpbuyanov commented on cmd/shortener/main.go
> +	logger := logrus.New()
но при этом оставить в main?

2024-05-07 09:19 UTC, vpbuyanov commented on cmd/shortener/main.go
> +	logger := logrus.New()
убрал в сервисы

2024-05-07 09:30 UTC, vpbuyanov commented on internal/services/url.go
> +func New() URL {
убрал все интерфейсы что были

2024-05-07 09:39 UTC, vpbuyanov commented on internal/services/url.go
> +		switch randNumber {
изменил

2024-05-07 09:39 UTC, vpbuyanov commented on Makefile
> +dev:
добавил

2024-05-10 14:28 UTC, s-shpak commented on cmd/shortener/main.go
> +		panic(err)
Потому что паники - мехнаизм для обработки других ситуаций

2024-05-10 14:30 UTC, s-shpak commented on internal/app/app.go
> +func (app *app) Run(ctx context.Context, log *logrus.Logger) error {
Не забывай про YAGNI

2024-05-10 14:34 UTC, s-shpak requested changes

2024-05-10 14:34 UTC, s-shpak commented on internal/services/url.go
> +	strShortURL := []rune("abcdefghijklmnopqrstuvwxyz" + "ABCDEFGHIJKLMNOPQRSTUVWXYZ" + "0123456789")
Ты каждый раз в рантайме создаешь 3 строки при вызове этой функции - это ненужная трата времени. Вынеси это лучше в константу

2024-05-10 14:34 UTC, s-shpak commented on internal/services/url.go
> +	var b strings.Builder
`strings.Builder` дорогой. Инициализируй лучше слайс и заполняй его

2024-05-10 14:34 UTC, s-shpak commented on internal/repos/repos.go
> +func (u *URL) CreateShortURL(url string) string {
Мы обсуждали, что генерация и сохранение ссылок должны быть независимыми. Ты решил это не делать ?

2024-05-10 14:49 UTC, vpbuyanov commented on internal/repos/repos.go
> +func (u *URL) CreateShortURL(url string) string {
а почему сейчас это зависимо и от чего это зависимо?

2024-05-10 14:49 UTC, vpbuyanov commented on internal/services/url.go
> +	var b strings.Builder
хорошо

2024-05-10 14:49 UTC, vpbuyanov commented on internal/services/url.go
> +	strShortURL := []rune("abcdefghijklmnopqrstuvwxyz" + "ABCDEFGHIJKLMNOPQRSTUVWXYZ" + "0123456789")
хорошо

2024-05-10 23:20 UTC, vpbuyanov commented on internal/repos/repos.go
> +func (u *URL) CreateShortURL(url string) string {
добавил новый слой UseCase для бизнес логики и вынес туда генерацию и проверки для ссылок 
сохранение оставил в repos

2024-05-11 12:56 UTC, s-shpak requested changes

2024-05-11 12:56 UTC, s-shpak commented on internal/repos/repos.go
> +	shortURL["abcdefgG12"] = "https://google.com"
Зачем ты добавляешь какие-то значения при инициализации ? Если это для тестов, то делай это сразу в тестах

2024-05-11 12:56 UTC, s-shpak commented on internal/usecase/url.go
> +	u.urlRepos.SaveShortURL(url, shortURL)
Если три раза не получится сгенерировать уникальную ссылку, то этот вызов все равно будет сделан

2024-05-11 12:56 UTC, s-shpak commented on internal/services/logger.go
> +	"github.com/sirupsen/logrus"
`logrus` заархивирован, используй лучше `zap`

2024-05-11 12:56 UTC, s-shpak commented on internal/handlers/shorter_test.go
> +					panic(err)
Паниковать не надо даже в тестах

2024-05-11 21:01 UTC, vpbuyanov commented on internal/repos/repos.go
> +	shortURL["abcdefgG12"] = "https://google.com"
ну такое нельзя было провернуть до этого так как не было разделения на слои сейчас такое есть и я исправлю спасибо

2024-05-11 21:02 UTC, vpbuyanov commented on internal/handlers/shorter_test.go
> +					panic(err)
хорошо 
хочется подробнее про паники услышать на вебинаре даже если там это будет вскользь

2024-05-13 22:02 UTC, s-shpak approved these changes

2024-05-16 10:13 UTC, merged